name: Test Foundry Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # Explicit submodule checkout

      - name: Cache Foundry toolchain
        uses: actions/cache@v3
        with:
          path: ~/.foundry
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/*.toml') }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes || exit 1  # Ensure build step fails if there's an error
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv || exit 1  # Ensure tests step fails if there's an error
        id: test
